# Generated by Django 4.0.5 on 2022-06-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_image', models.ImageField(upload_to='sp_images', verbose_name='image')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('price', models.FloatField(verbose_name='price')),
                ('availability', models.CharField(choices=[('còn hàng', 'Còn Hàng'), ('hết hàng', 'Hết Hàng'), ('dừng sản xuất', 'Dừng Sản Xuất')], max_length=20, verbose_name='availability')),
                ('condition', models.CharField(choices=[('mới', 'Mới'), ('cũ', 'Cũ'), ('sale', 'Sale')], max_length=20, verbose_name='condition')),
                ('brand', models.CharField(choices=[('chanel', 'CHANEL'), ('gucci', 'GUCCI'), ('dior', 'DIOR'), ('louis vuitton', 'LOUIS VUITTON'), ('dolce & cabbana', 'DOLCE & GABBANA'), ('hermes', 'HERMÈS'), ('versace', 'VERSACE'), ('prada', 'PRADA')], max_length=20, verbose_name='brand')),
                ('kind_of_sp', models.CharField(choices=[('men', 'Nam'), ('women', 'Nữ'), ('children', 'Trẻ Em')], max_length=20, verbose_name='product type')),
            ],
        ),
    ]
