# Generated by Django 4.0.5 on 2022-06-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_image', models.ImageField(upload_to='shoe_images', verbose_name='shoe image')),
                ('shoe_name', models.CharField(max_length=200, verbose_name='shoe name')),
                ('shoe_company', models.CharField(choices=[('NIKE', 'NIKE'), ('UNDER ARMOUR', 'UNDER ARMOUR'), ('ADIDAS', 'ADIDAS'), ('PUMA', 'PUMA'), ('ASICS', 'ASICS'), ('vn', 'Hàng nội địa')], max_length=50, verbose_name='shoe company')),
                ('price', models.IntegerField(verbose_name='price')),
                ('size', models.IntegerField(verbose_name='size of shoes')),
                ('availability', models.CharField(choices=[('còn hàng', 'Còn Hàng'), ('hết hàng', 'Hết Hàng'), ('dừng sản xuất', 'Dừng Sản Xuất')], max_length=20, verbose_name='availability')),
                ('condition', models.CharField(choices=[('mới', 'Mới'), ('cũ', 'Cũ'), ('sale', 'Sale')], max_length=20, verbose_name='condition')),
                ('kind_shoe', models.CharField(choices=[('giày thể thao', 'Giày Thể Thao'), ('giày tây', 'Giày Tây'), ('thường', 'Thường')], max_length=20)),
                ('kind_of_shoe', models.CharField(choices=[('men', 'Nam'), ('women', 'Nữ'), ('children', 'Trẻ Em')], max_length=20, verbose_name='product type')),
            ],
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
    ]
