# Generated by Django 4.0.5 on 2022-06-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0003_bag_alter_sanpham_brand_alter_shoe_shoe_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoiThat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noithat_image', models.ImageField(upload_to='noithat_images')),
                ('name', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('kind_of_interior', models.CharField(choices=[('Không gian phòng khách', 'Không gian phòng khách'), ('Đồ trang trí', 'Đồ trang trí'), ('Không gian phòng ngủ', 'Không gian phòng ngủ'), ('Không gian phòng ăn', 'Không gian phòng ăn')], max_length=100)),
                ('product_interior', models.CharField(choices=[('sofa', 'Sofa'), ('bàn', 'Bàn'), ('ghế', 'Ghế'), ('tủ', 'Tủ'), ('kệ', 'Kệ')], max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[('còn hàng', 'Còn Hàng'), ('hết hàng', 'Hết Hàng'), ('dừng sản xuất', 'Dừng Sản Xuất')], max_length=20, verbose_name='availability')),
                ('condition', models.CharField(choices=[('mới', 'Mới'), ('cũ', 'Cũ'), ('sale', 'Sale')], max_length=20, verbose_name='condition')),
            ],
        ),
    ]
