# Generated by Django 4.0.5 on 2022-06-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0005_tui_delete_bag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image_blog', models.ImageField(upload_to='blog_images')),
                ('time_created', models.TimeField(auto_now=True)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
